### ISSUE TITLE
Implement query parameter

### ISSUE THREAD

**Issue by n-ce** [shailendramaurya/racoon#1]
Allow Using Query Parameter to directly load link into website without typing in input.
e.g. https://shailendramaurya.github.io/racoon/?url=https://youtu.be/elevenevele

On another note, this will allow the integration with ytify https://github.com/n-ce/ytify/issues/128

**Comment by n-ce** [comment]
I just found out it already uses a query param for the pwa web share api, that will do the job!

**Comment by shailendramaurya** [comment]
> I just found out it already uses a query param for the pwa web share api, that will do the job!

Same, I was saying, just replace the "url" with "link" in above example......
And thanks, for considering this project for integration :-)
