### ISSUE TITLE
Display codec in download table

### ISSUE THREAD

**Issue by n-ce** [shailendramaurya/racoon#2]
have another column displaying codec , this would be beneficial to know the quality difference apart from bitrates.

**Comment by shailendramaurya** [comment]
> have another column displaying codec , this would be beneficial to know the quality difference apart from bitrates.

Is this really needed?? Becouse, all the audio files will be downloaded as .mp3 and all videos as .mp4 !

**Comment by n-ce** [comment]
If the file is not being transcoded then it is needed because there is a respectable difference between mp3, opus and m4a codecs. Some people prefer one over the other.
