### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by dangerrxf** [shailendramaurya/racoon#7]
i get this when i put any youtube link (only tested on youtube) and try to download it

**Comment by dangerrxf** [comment]
ok nvm its because cobalt is browning out its api i dont know wether to keep this open

**Comment by shailendramaurya** [comment]
> ok nvm its because cobalt is browning out its api i dont know wether to keep this open

Will spin up own api server soon

**Comment by nms808** [comment]
Reconfirming the same issue, it's been like this for over a month now and I've tried many random times if that helps any:

TypeError: NetworkError when attempting to fetch resource.

"Will spin up own api server soon" (Any status update on this?) Thank you!

**Comment by shailendramaurya** [comment]
> Reconfirming the same issue, it's been like this for over a month now and I've tried many random times if that helps any:
> 
> TypeError: NetworkError when attempting to fetch resource.
> 
> "Will spin up own api server soon" (Any status update on this?) Thank you!

Apologies for the delay in getting back to this issue...... Server on the way :)
